### ISSUE TITLE
Access to child array in template

### ISSUE THREAD

**Issue by i9ii9i** [telerik/ui-for-blazor-examples#1]
Data Grid:
How do I get access to a child collection in the data object when using a column template.
The grid is bound to a List<T>.

I tried various methods to show the child collection data, but I get null references errors or I get no errors but no child data.

Thank you

**Comment by jivanova** [comment]
@i9ii9i  I see that you've closed the issue and I hope that you've managed to get access to the child collection.  

We have added a sample app where you could play more with the Grid and see how the templates are defined. For reference, you could use the Templates as follows:

[Grid Index page](https://github.com/telerik/ui-for-blazor-examples/blob/master/TelerikBlazor/TelerikBlazor.App/Pages/Grid/Index.cshtml#L8): 
``` cshtml
<KendoGridColumn Field="Date">
      <Template>
          @((context as WeatherForecast).Date.ToString("MMMM dd, yyyy"))
      </Template>
</KendoGridColumn>
```

Let me know if you have further questions.
