### ISSUE TITLE
Bug - Getting error when using Grid.

### ISSUE THREAD

**Issue by BenHayat** [telerik/ui-for-blazor-examples#16]
Hello;
I've just installed Telerik Blazor by downloading the package from
 https://www.telerik.com/download-trial-file/v2-b/ui-for-blazor.
And saved it to my desktop
Then in the nuget I had to create a new entry for telerik.com and point it to my desktop and do update first. like the following:

![nuget-telerik](https://user-images.githubusercontent.com/7861196/56256871-71ad7780-6098-11e9-93f7-5a8a02e99b86.png)

After that I followed setting up the project. Then in my home page, I pasted the grid example:

![code](https://user-images.githubusercontent.com/7861196/56258165-a15e7e80-609c-11e9-8bd1-104941bf0d6a.png)

when I run the app, I get the following error:

Unhandled exception rendering component: Cannot provide a value for property 'DataSource' on type 'Telerik.Blazor.Components.Grid.TelerikGrid`1[[System.Object, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'. There is no registered service of type 'Telerik.Blazor.Data.ITelerikDataSource'.
System.InvalidOperationException: Cannot provide a value for property 'DataSource' on type 'Telerik.Blazor.Components.Grid.TelerikGrid`1[[System.Object, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'. There is no registered service of type 'Telerik.Blazor.Data.ITelerikDataSource'.

----------
Have I done something wrong with the install or is this a bug?

**Comment by jivanova** [comment]
Hi, 

The services are registered via the **AddTelerikBlazor** method:

```
public void ConfigureServices(IServiceCollection services)
{
    services.AddTelerikBlazor();
}
```

https://github.com/telerik/ui-for-blazor-examples/blob/master/TelerikBlazor.Client/Startup.cs#L11

We saw that that this information is missing in our GettingStarted articles. So, thanks to your report, we will enhance them to include the service registration. 

https://docs.telerik.com/blazor/getting-started/client-blazor

**Comment by BenHayat** [comment]
@jivanova 
Thank you.
I tried other components and worked without registering the Telerik services, so I didn't even think about that.

There is also one other thing in the installation missing.
When I downloaded the nuget package, I save it on my desktop. Just like the above picture shows, I had to create a new Telerik.com entry and point the "Package Source" to my desktop. This part is missing in your installation. Otherwise nuget won't find your online nuget package to install.

Third suggestion: As of next Preview of Blazor, "AddTagHelper" is gone. So in your doc, that needs to be adjusted.

![tag](https://user-images.githubusercontent.com/7861196/56263574-7a5e7780-60b1-11e9-921b-070f64dd31e4.png)

**Comment by jivanova** [comment]
Hey, 

We just added the service step in our docs: https://docs.telerik.com/blazor/getting-started/client-blazor

Indeed, we could improve our description that **Local Nuget Feed** should be created once the nuget is downloaded. Once done, the nuget should appear in our Telerik Private Nuget Feed and newer versions will automatically display. [(telerik nuget feed setup)](https://docs.telerik.com/blazor/installation/nuget)

Thank you for pointing the addTagHelper change. We'll take care of updating the article : )

**Comment by BenHayat** [comment]
@jivanova 
Now that I have your attention, one more question.

Take a look at the image below, and you can see DevEx offers a link for the nuget source where as Telerik, we have to download a package specific to a version (.4xxx) and then manually create a private nuget.

![dev](https://user-images.githubusercontent.com/7861196/56264787-919f6400-60b5-11e9-98e6-9910cf579a7b.png)

Why can't telerik just offer a link as well to make it easier for all the new comers?

**Comment by jivanova** [comment]
Thank you so much for your feedback!

Basically, the setup of Telerik Nuget is similar to the one for DevEx:
```
Telerik NuGet

https://nuget.telerik.com/nuget
```
However, there is an issue with the automatically display of Blazor package without being downloaded first. I agree that if we could skip this step, it will be much easier for new comers. We really appreciate your feedback and will review the case.

**Comment by BenHayat** [comment]
Well, I had been looking for this link throughout your docs and could not find it

https://nuget.telerik.com/nuget

So resorted to pointing to a local file, which can get obsolete fast with new updates.
I just changed it to this link and works to.
So please update your docs with this link for Telerik Nuget.

**Comment by ivanchev** [comment]
Once we release an official v1 for the product the NuGet issue will be resolved, and the manual download step will not be needed, and you could simply reference the components from the Telerik private nuget feed.

**Comment by BenHayat** [comment]
@ivanchev 
Excellent and fair enough on timing. If you like, you can close this thread or leave it open for others's comments.

**Comment by ivanchev** [comment]
I'll close this one as resolved. Feel free to open new ones for other issues :)
