### ISSUE TITLE
Sharing info with Team

### ISSUE THREAD

**Issue by BenHayat** [telerik/ui-for-blazor-examples#17]
So, we got the announcement today that .Net core 3 preview 4 is out. So I installed the new preview, then installed VS19 Preview and according to the instructions from Dan Roth, I had to run the following command to install the Blazor (client side) template into VS19.

> dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview4-19216-03
However, I got error that was related to the Telerik Nuget that I already had in my VS system.
So I went to NuGet Settings and deleted the entry for telerik.com and it's nuget source. Then ran the above command and worked fine.

So I thought I share this with you, where for the next few previews, people may encounter such problem. I suppose once you have a new update for Preview 4, I can then go back and create a new Package source that will point to 
https://nuget.telerik.com/nuget

Hope this info helps!
..Ben

**Comment by ivanchev** [comment]
Thank you Ben. We'll release a compatible version 0.5 that works with Preview 4 in by the middle of this week. It should resolve all of the issues.

**Comment by BenHayat** [comment]
Thank you Sir!

**Comment by BenHayat** [comment]
@ivanchev 

Hi;
I'd like to make a couple of suggestions: 
From this point on, till we go RTM:
1) It would be great to have two separate demos, one base on Server-side model, and the other based on client-side.
2) On the top bar of the demo, it should identify 3 things:
a) Which model the user is running - this way we can gauge the load time and reaction time of each components.
b) What version of MSFT Blazor is it based on - If we find issues we know what version it is.
c) Similarly what Telerik Version of Blazor are we running.

Hope this helps!
..Ben

**Comment by ivanchev** [comment]
Good suggestion. This however brings the burden of maintaing two demo sites, and splitting the traffic between the two, which is not good. I see your points though, and we will give this a thorough though.

Specifying the Telerik version is however simple enough, and we can think of a way to incorporate it in a visible place in the demos.

**Comment by BenHayat** [comment]
@ivanchev;
As a previous gen Telerik MVP, I used to make different suggestions & discussions with the team during product development, and I'd like to do so, if you don't mind.

> This however brings the burden of maintaining two demo sites, and splitting the traffic between the two, which is not good.

I understand and here is my two cents.
As of now, MSFT is focusing on the server side to be part of .Net Core 3 and the client side for the future.
Although from "Component" point of view, these two models may look & behave the same, but for us the final product developers, the whole strategy (especially dealing with database CRUD) each model presents it's own direction and strategy.
So I do understand your point clearly. Since the server side is the more immediate product, why don't we focus on the server side demo for now, until MSFT gets the client side sorted out?

Secondly, are you guys more focusing on demoing your "components" in Blazor or are you planning to extend the demos to actually show a simple business application and how components make up the whole app? If you are ONLY interested to demo the "Components", then it's up to you guys which model you pick.
Hope this helps!

Thanks!
..Ben

**Comment by ivanchev** [comment]
Thank you for the feedback. To address your points:

We did try to use the Server side for the demos, but we ran into a lot of issues with the SignalR connection, and believe it or not, the Client solution is more stable for us at this point. We do plan to continue comparing the two models, and choose the best one for the demos site as the framework evolves

In terms of the purpose of the demos - it is to demonstrate the components and their individual features in isolated sample pages. To this end, the demos site's only purpose is to host the components in a native environment. As we've done in the past, we do plan to have dedicated sample applications, that demonstrate a more wholistic approach to building an application, and there we could dive deeper into the hosting models and other "SPA" aspects of Blazor.

**Comment by BenHayat** [comment]
Thank you for your clear answers. I'll be advancing along Telerik's team , and I'll watch which one Telerik favors more. 
Earlier on versions, I did notice some issues with SignalR loosing connection and the client would become unresponsive, if the client was idle for a while. In someways, I do like the server side better, less data being moved backed and forth, but the whole idea of SignalR trying to have a "True" replication of server on the clients side, I'm not 100% sold on the idea. The good old client execution should provide the real mode to the user.

Thanks again!

**Comment by ivanchev** [comment]
Clearing the dust a little from this issue, but just to notify here as well that we've just updated the live demos site to use ServerSide Blazor. :)
