### ISSUE TITLE
Height parameter causes grid to not display

### ISSUE THREAD

**Issue by EdCharbeneau** [telerik/ui-for-blazor-examples#3]
When the Height parameter is set, the grid does not render.

I don't believe Height is a valid parameter in version Kendo.Blazor 0.1.0

https://github.com/telerik/ui-for-blazor-examples/blob/c5bc6dee26d5ce36622238034f5aa9ffea3e781a/TelerikBlazor/TelerikBlazor.App/Pages/Grid/DataBind.cshtml#L9

**Comment by ivanchev** [comment]
Don't seem to be able to reproduce it. Fresh copy of the repo, Add DB Connection String to User Secrets and the height is properly set.
